pipeline{
  agent any

  parameters {
    choice(name: 'ACTION', choices: ['dev-apply', 'prod-apply', 'dev-destroy', 'prod-destroy'], description: 'Choose Environment')
  }

  stages{
    stage('VPC Apply'){
      steps{
        sh '''
          cd vpc
          make ${ACTION}
         '''
      }
    }
  }
}