variable "VPC_PRIVATE_CIDR"     {}
variable "VPC_PUBLIC_CIDR"      {}
variable "PUBLIC_SUBNET_CIDRS"  {}
variable "PRIVATE_SUBNET_CIDRS" {}
variable "SUBNET_AZ"            {}
variable "ENV"                  {}
variable "DEFAULT_VPC_ID"       {}
variable "DEFAULT_VPC_CIDR"     {}
variable "INTERNAL_DNS_ZONE_ID" {}